### PR TITLE
Remove all network request code, drop unnecessary dependencies.

### PR DESCRIPTION
**Pull request by SomeCrazyGuy**
This patch removes the dependency on libcurl and openssl. These dependencies are used for fetching and verifying license data as well as create translations for UI elements through google translate. With this patch all code for performing network requests is removed.

### CODE REVIEW

**Comment by thesourcerer8** [comment]
Why do you want to remove the Google Translate function?

**Comment by SomeCrazyGuy** [comment]
My rational is that translation and internationalization should be performed using more standard tools -like gettext- which integrates well with GTK applications. If we want to add quick and dirty support for another language with google translate we can use google translate on the .po files generated by gettext.

**Comment by thesourcerer8** [comment]
Oh, I didn't noticed that gettext wasn't used. Hmm, yes, porting to gettext first makes sense to me then.
But we could already remove the server part which was only used for licensing. Let me know if I should deny this pullrequest.

**Comment by SomeCrazyGuy** [comment]
Deny this pull request, what I will do is remove the smtp code in one request and submit another pull request to make libcurl an optional dependency. Having a minimal build configuration will make it easier to have a windows port of the viewer build target.

**Pull request closed without merging**
